FROM ubuntu:20.04

RUN apt-get update && apt-get DEBIAN_FRONTEND=noninteractive install -y \
	byobu hollywood locate mlocate \
	&& rm -rf /var/lib/apt/lists/* && updatedb

ENV HOME /home/user
RUN useradd --create-home --home-dir $HOME user \
	&& chown -R user:user $HOME

WORKDIR $HOME
USER user

CMD [ "hollywood" ]
